language: generic
script: 
  - docker run --rm -v ${TRAVIS_BUILD_DIR}:/project antonkrug/verilator-lcov-slim:da1cef5 bash -c "cd /project && npm install"

  - mkdir -p ${TRAVIS_BUILD_DIR}/images
  - chmod a+rw ${TRAVIS_BUILD_DIR}/images
  - rm ${TRAVIS_BUILD_DIR}/images/*
  - docker run --rm -v ${TRAVIS_BUILD_DIR}:/project wernight/phantomjs:2.1.1 bash -c "/project/images_src/generate_images.sh"

  - docker run --rm -v ${TRAVIS_BUILD_DIR}:/project antonkrug/verilator-lcov-slim:da1cef5 bash -c "cd /project && npm run-script lint"
  - docker run --rm -v ${TRAVIS_BUILD_DIR}:/project antonkrug/verilator-lcov-slim:da1cef5 bash -c "cd /project && npm run-script build"
  - docker run --rm -v ${TRAVIS_BUILD_DIR}:/project antonkrug/verilator-lcov-slim:da1cef5 bash -c "cd /project && npm run-script run"
  - docker run --rm -v ${TRAVIS_BUILD_DIR}:/project --env-file <(env) antonkrug/verilator-lcov-slim:da1cef5 bash -c "cd /project && npm run-script coverage:coveralls"
  - docker run --rm -v ${TRAVIS_BUILD_DIR}:/project antonkrug/verilator-lcov-slim:da1cef5 bash -c "cd /project && npm run-script coverage:html-report"